apiVersion: batch/v1
kind: Job
metadata: 
  name: hellojob
spec:
  template:
    metadata:
      name: hellojob
    spec:
      containers:
      -  name: hello
         image: busybox
         command: ["echo","hello k8s"]
      restartPolicy: Never
