apiVersion: v1
kind: Service
metadata:
  name: nginx-headle-svc
  namespace: default
  labels:
    app: nginx
spec:
  selector:
    app: nginx-sts
  ports:
    - name: http
      port: 80
  clusterIP: None