kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mycluster
networking:
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  kubeProxyMode: "ipvs"
nodes:
- role: control-plane
- role: worker
- role: worker
  