---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: deploy-myapp
  type: NodePort  
  ports:
  - port: 80
    targetPort: 80
    nodePort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: deploy-myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx:1.14
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/
        - name: alpine
          image: alpine:3.12
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: html
              mountPath: /data/
          command: ["/bin/sh", "-c", "sleep 3600"]
      volumes:
        - name: html
          emptyDir: {}
            