apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv-nfs
  labels:
    pv: pv-nfs
spec:
  capacity:
    storage: 50Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /data/k8s
    server: 81.70.54.47
