apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-service
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort # 指定服务类型为 NodePort
  ports:
    - port: 8080 # 指定集群内部 service 的端口
      targetPort: 80  #指定 Pod 的端口
      nodePort: 30000 # 指定外部连接的端口
  selector:
    app: nginx   # 标签选择器，选择带有 app=tomcat 的 Pod
