apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: root_passwd
          volumeMounts:
            - name: mysql
              mountPath: /etc/mysql/mysql.conf.d
      volumes:
        - name: mysql
          configMap:
            name: mysql-config
